#!/bin/bash
# Open test URLs in Safari and print verification checklist

URLS=(
  "https://www.imdb.com/title/tt1375666/"
  "https://www.rottentomatoes.com/m/the_dark_knight"
  "https://www.rottentomatoes.com/tv/breaking_bad"
  "https://www.themoviedb.org/movie/27205-inception"
  "https://www.themoviedb.org/tv/1396-breaking-bad"
  "https://letterboxd.com/film/inception/"
  "https://thetvdb.com/movies/oppenheimer"
  "https://thetvdb.com/series/breaking-bad"
)

echo "Opening test URLs in Safari..."
for url in "${URLS[@]}"; do
  open -a Safari "$url"
  sleep 0.5
done

echo ""
echo "=== Verification Checklist ==="
echo ""
echo "IMDB (imdb.com/title/tt1375666):"
echo "  [ ] Radarr button appears near title"
echo "  [ ] Sonarr button does NOT appear (it's a movie)"
echo "  [ ] Buttons have right-side spacing"
echo ""
echo "RT Movie (rottentomatoes.com/m/the_dark_knight):"
echo "  [ ] Radarr button appears in top-right corner (fixed position)"
echo "  [ ] Button is clickable"
echo "  [ ] Title extracted correctly"
echo ""
echo "RT TV (rottentomatoes.com/tv/breaking_bad):"
echo "  [ ] Sonarr button appears in top-right corner (fixed position)"
echo "  [ ] Button is clickable"
echo "  [ ] Title extracted correctly"
echo ""
echo "TMDb Movie (themoviedb.org/movie/27205):"
echo "  [ ] Radarr button appears near title"
echo "  [ ] Sonarr button does NOT appear"
echo ""
echo "TMDb TV (themoviedb.org/tv/1396):"
echo "  [ ] Sonarr button appears near title"
echo "  [ ] Radarr button does NOT appear"
echo ""
echo "Letterboxd (letterboxd.com/film/inception):"
echo "  [ ] Radarr button appears near title"
echo ""
echo "TheTVDB Movie (thetvdb.com/movies/oppenheimer):"
echo "  [ ] Radarr button appears near title"
echo "  [ ] Sonarr button does NOT appear"
echo ""
echo "TheTVDB Series (thetvdb.com/series/breaking-bad):"
echo "  [ ] Sonarr button appears near title"
echo "  [ ] Radarr button does NOT appear"
echo ""
echo "Popup Permission Banner:"
echo "  [ ] On a supported page with permission: green 'active' banner"
echo "  [ ] On a supported page without permission: orange 'needs permission' banner"
echo "  [ ] On an unsupported page (e.g. google.com): no banner shown"
